name: Install Sample App

on:
  workflow_dispatch:

permissions:
  id-token: write # required to use OIDC authentication
  contents: read # required to checkout the code from the repo

jobs:
  helm:
    name: Create App - Helm
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: eks
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Terraform 1.3.0
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.0

    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::${{ secrets.ACCOUNT_NUM }}:role/ex-iam-github-oidc
        role-duration-seconds: 900 # the ttl of the session, in seconds.
        aws-region: eu-west-1 # use your region here.

    - name: aws-cli
      id: install-aws-cli
      uses: unfor19/install-aws-cli-action@master
      with:
        version: 1.19.100
    - run: aws eks update-kubeconfig --name eks-cluster --region eu-west-1 --kubeconfig '~/.kube/config'
      working-directory: /

    - name: install-helm
      id: install
      uses: azure/setup-helm@v3
      with:
         version: 'v3.6.1' # default is latest (stable)

    - name: helm-deploy
      id: deploy
      run: |
        helm install onlineboutique /home/runner/work/aws-eks-terraform/aws-eks-terraform/online-boutique-tf/helm --namespace=app --create-namespace --kubeconfig /home/runner/.kube/config
      working-directory: /
        