name: Terraform

on:
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  terraform:
    name: Plan / Apply
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: eks
    permissions:
      contents: read
      pull-requests: write
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Terraform 1.3.0
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.0

    - name: Terraform Format
      id: fmt
      run: terraform fmt -check
      working-directory: ./eks-infra
      continue-on-error: true

    - name: Terraform Init
      id: init
      run: terraform init
      working-directory: ./eks-infra

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color
      working-directory: ./eks-infra
      continue-on-error: true

    - name: Terraform Destroy
      id: apply
      run: terraform destroy -auto-approve -input=false
      working-directory: ./eks-infra